### ISSUE TITLE
Swift 3.0

### ISSUE THREAD

**Issue by kanzelsberger** [feedhenry/fh-ios-swift-sdk#21]
Most of the opensource frameworks are now migrated to Swift 3.0, but FeedHenry still won't compile in Xcode 8... any plans to create a Swift3 branch? Migration should be fairly easy.

**Comment by corinnekrych** [comment]
Xcode 8 compilation with swift 2.3 is planned for RHMAP-3.15 coming very soon
Swift3 support will be soon after

**Comment by jcesarmobile** [comment]
We have released 4.2.0 with Swift 2.3 support and 5.0.0 with Swift 3 support.
